name: openAPI linting test
on:
  workflow_dispatch:
    inputs:
      POC_ENV:
        description: 'The target build environment'
        required: true
        type: choice
        default: openAPI
        options:
          - openAPI
          - ecs
          - prod
  workflow_call:
    inputs:
      TARGET_BRANCH:
        description: "The target branch"
        default: ""
        type: string

jobs:
  POC-OpenAPI-linting-Testting:
    if: github.event.inputs.POC_ENV == 'openAPI'
    name: OpenAPI Linting Testting
    environment: building_variables
    runs-on: [poc]
    steps:
    - uses: schemathesis/action@v1
      with:
        schema: "https://example.schemathesis.io/openapi.json"
  Build-push-from-ECS:
    if: github.event.inputs.POC_ENV == 'ecs'
    name: Building at ECS
    environment: building_variables
    runs-on: [ECS-official-website-Linux]
    outputs:
      IMAGE: ${{ steps.cn-image.outputs.image }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.TARGET_BRANCH || '' }}
        ssh-key: ${{ secrets.ECS_SSH_PRIVATE_KEY }}
    - name: Login to AlibabaCloud ACR Build, tag, and push image to Aliyun ACR
      id: cn-image
      env:
        IMAGE_TAG: ${{ github.sha }}
        ACR_REGISTRY: "registry.cn-shenzhen.aliyuncs.com/xrspace-server"
        ACR_REPOSITORY: "webportal-v2"
        DOCKER_BUILDKIT: True
      shell: bash
      run: |
        # Build a docker container and
        # push it to ACR so that it can
        # be deployed to ECS.
        ######## ACR push time is too long and temporarily blocked ######################
        # docker login --username=${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} $ACR_REGISTRY
        # docker push "$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG" 
        go env -w GOPROXY=https://goproxy.cn
        pre-commit run --all-files
        echo "image='$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG'" >> $GITHUB_OUTPUT

        if [[ -z "$(docker inspect $(docker images -q)|grep $IMAGE_TAG)" ]];then
          pushd deployment/ECS || exit 1
            if [[ -n "$(docker images -f label=app=official-website-v2 -q)" ]];then
              docker-compose down
              docker rmi $(docker images -f label="app=official-website-v2" -q)
            fi
          popd
          docker build -t "$ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG" . --build-arg locales="tw,us" --build-arg defaultLocale="us" -f deployment/ECS/Dockerfile
        fi

  Deploy_to_EC2:
    if: github.event.inputs.POC_ENV == 'ec2'
    environment: deploy_variables_for_dev
    needs: Build-push-from-EC2
    runs-on: [EC2-official-website-Linux]
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: ap-southeast-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Terraform Apply
      run: |
        pushd infra/EC2/ || exit 1
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve
        popd
        pre-commit run --all-files
        ansible-lint deployment
    - name: Ansible Deploy to EC2
      shell: bash
      run: |
        cd deployment/EC2/ || exit 1
        echo '${{ secrets.PEM }}' > ec2.pem 
        chmod 400 ec2.pem
        ansible-playbook -i hosts provision.yml
  Deploy_to_ECS:
    if: github.event.inputs.POC_ENV == 'ecs'
    environment: deploy_variables_for_dev
    needs: Build-push-from-ECS
    runs-on: [ECS-official-website-Linux]
    steps:
    - name: Deploy to ECS
      shell: bash
      run: |
        echo "nuxt_public_api_base='NUXT_PUBLIC_API_BASE: https://webportal-cms-dev.xrspace.com.cn/api'"> ~/office-website-v2/env.yaml
        pushd deployment/ECS/ || exit 1
        export IMAGE='${{ needs.Build-push-from-ECS.outputs.IMAGE }}'
        docker-compose down
        docker-compose up -d
